### ISSUE TITLE
Feature Request: Prepare Docker for local use

### ISSUE THREAD

**Issue by uh-zz** [uh-zz/dynamoose-go#5]
## Feature Request

Prepare an environment with local dynamo and dynagoose clients running on docker-compose

**Expected behavior/code**

```yaml
services:
     dynamo:
          ...
     dynagoose:
          ...
```
